<?php
/**
 * @file
 * Souriau Commom Constants.
 */

define('SOURIAU_COMMON_VAR_HEADER_MENU', 'main-menu');
define('SOURIAU_COMMON_DOMAIN_CENTRAL', 1);
define('SOURIAU_COMMON_DOMAIN_INTERNATIONAL', 2);
define('SOURIAU_COMMON_VIEW_QUERY_GET_MENU_ITEMS', 'souriau_query_get_menu_elements');
define('SOURIAU_COMMON_VAR_DEFAULT_LNG', 'en-en');
define('SOURIAU_COMMON_PRODUCT_LANDING_CT', 'productlanding');
define('SOURIAU_COMMON_APPLICATION_LANDING_CT', 'applicationlanding');
define('SOURIAU_COMMON_CAPABILITIES_LANDING_CT', 'capabilitieslanding');
define('SOURIAU_COMMON_CAPABILITY_DOMAIN_CT', 'capabilitydomain');
define('SOURIAU_COMMON_APPLICATION_DOMAIN_CT', 'applicationdomain');
define('SOURIAU_COMMON_CATEGORY_CT', 'category');
define('SOURIAU_COMMON_SUBCATEGORY_CT', 'subcategory');
define('SOURIAU_COMMON_APPLICATION_CT', 'application');
define('SOURIAU_COMMON_CAPABILITY_CT', 'capability');
define('SOURIAU_COMMON_PRODUCT_RANGE_CT', 'productrange');
define('SOURIAU_COMMON_PRODUCT_RANGE_HUB_CT', 'productrangehub');
define('SOURIAU_COMMON_NEWS_CT', 'news');
define('SOURIAU_COMMON_NEWS_LANDING_CT', 'news_landing');
define('SOURIAU_COMMON_CENTRAL_DOMAIN_ID', 1);
define('SOURIAU_COMMON_PART_NUMBER_CT', 'product');
define('SOURIAU_COMMON_TOOL_CT', 'tool');
define('SOURIAU_COMMON_TOOLKIT_LANDING', 'toolkitlanding');
define('SOURIAU_COMMON_GENERIC_LANDING', 'genericlanding');
define('SOURIAU_COMMON_RESOURCE_CT', 'resource');
define('SOURIAU_COMMON_VQ_PARTNUMBER_BY_SKU', 'souriau_query_get_partnumber_by_sku');
define('SOURIAU_WEBFORM_CONTACTFORM_NID', variable_get('souriau_webform_contactform_nid', 707));
define('SOURIAU_COMMON_IMAGEMAP_LAST', 'last');
define('SOURIAU_COMMON_WEBMASTER', variable_get('souriau_common_webmaster_mail', 'webmaster@souriau.com'));
define('SOURIAU_COMMON_CMS_PAGE', 'cms_page');
define('SOURIAU_CAREER_LINK', variable_get('ect_site_career_link', 'https://careers.esterline.com/ListJobs/All'));

// Contexts.
define('SOURIAU_COMMON_T_USER', 'SOURIAU: user');
define('SOURIAU_COMMON_T_ADMIN', 'SOURIAU: admin area');
define('SOURIAU_COMMON_T_OTHER', 'SOURIAU: other');
define('SOURIAU_COMMON_T_COMMERCE', 'SOURIAU: commerce');
define('SOURIAU_COMMON_T_FOOTER', 'SOURIAU: footer');
define('SOURIAU_COMMON_T_HEADER', 'SOURIAU: header');
define('SOURIAU_COMMON_T_FACETS', 'SOURIAU: facets');
define('SOURIAU_COMMON_T_SKU', 'SOURIAU: sku attributes');
