<?php
/**
 * @file
 * souriau_ct_webform.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function souriau_ct_webform_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'dashboard_souriau_webforms';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Dashboard Souriau Webforms';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Products List';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'role';
  $handler->display->display_options['access']['role'] = array(
    10 => '10',
    11 => '11',
  );
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '25';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['style_plugin'] = 'table';
  $handler->display->display_options['style_options']['columns'] = array(
    'nid' => 'nid',
    'title_field' => 'title_field',
    'type' => 'type',
    'changed' => 'changed',
    'webform_submission_count_node' => 'webform_submission_count_node',
    'webform_results_1' => 'webform_results_1',
    'webform_results' => 'webform_results_1',
    'webform_results_2' => 'webform_results_1',
    'webform_edit' => 'webform_edit',
    'webform_edit_2' => 'webform_edit',
    'edit_node' => 'webform_edit',
    'webform_results_3' => 'webform_results_1',
  );
  $handler->display->display_options['style_options']['default'] = '-1';
  $handler->display->display_options['style_options']['info'] = array(
    'nid' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'title_field' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'type' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'changed' => array(
      'sortable' => 0,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'webform_submission_count_node' => array(
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'webform_results_1' => array(
      'align' => '',
      'separator' => ' &nbsp; ',
      'empty_column' => 0,
    ),
    'webform_results' => array(
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'webform_results_2' => array(
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'webform_edit' => array(
      'align' => '',
      'separator' => ' &nbsp; ',
      'empty_column' => 0,
    ),
    'webform_edit_2' => array(
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'edit_node' => array(
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'webform_results_3' => array(
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
  );
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  /* Field: Field: Title */
  $handler->display->display_options['fields']['title_field']['id'] = 'title_field';
  $handler->display->display_options['fields']['title_field']['table'] = 'field_data_title_field';
  $handler->display->display_options['fields']['title_field']['field'] = 'title_field';
  $handler->display->display_options['fields']['title_field']['empty'] = '[title]';
  $handler->display->display_options['fields']['title_field']['link_to_entity'] = 1;
  /* Field: Content: Type */
  $handler->display->display_options['fields']['type']['id'] = 'type';
  $handler->display->display_options['fields']['type']['table'] = 'node';
  $handler->display->display_options['fields']['type']['field'] = 'type';
  /* Field: Content: Updated date */
  $handler->display->display_options['fields']['changed']['id'] = 'changed';
  $handler->display->display_options['fields']['changed']['table'] = 'node';
  $handler->display->display_options['fields']['changed']['field'] = 'changed';
  $handler->display->display_options['fields']['changed']['date_format'] = 'short';
  $handler->display->display_options['fields']['changed']['second_date_format'] = 'search_api_facetapi_YEAR';
  /* Field: Webform: Webform submission count */
  $handler->display->display_options['fields']['webform_submission_count_node']['id'] = 'webform_submission_count_node';
  $handler->display->display_options['fields']['webform_submission_count_node']['table'] = 'node';
  $handler->display->display_options['fields']['webform_submission_count_node']['field'] = 'webform_submission_count_node';
  $handler->display->display_options['fields']['webform_submission_count_node']['label'] = 'Submissions Count';
  /* Field: Webform: Webform results link */
  $handler->display->display_options['fields']['webform_results_1']['id'] = 'webform_results_1';
  $handler->display->display_options['fields']['webform_results_1']['table'] = 'node';
  $handler->display->display_options['fields']['webform_results_1']['field'] = 'webform_results';
  $handler->display->display_options['fields']['webform_results_1']['relationship'] = 'nid';
  $handler->display->display_options['fields']['webform_results_1']['label'] = 'View';
  $handler->display->display_options['fields']['webform_results_1']['text'] = 'submissions';
  /* Field: Webform: Webform results link */
  $handler->display->display_options['fields']['webform_results']['id'] = 'webform_results';
  $handler->display->display_options['fields']['webform_results']['table'] = 'node';
  $handler->display->display_options['fields']['webform_results']['field'] = 'webform_results';
  $handler->display->display_options['fields']['webform_results']['relationship'] = 'nid';
  $handler->display->display_options['fields']['webform_results']['label'] = 'analysis';
  $handler->display->display_options['fields']['webform_results']['text'] = 'analysis';
  $handler->display->display_options['fields']['webform_results']['subpath'] = 'analysis';
  /* Field: Webform: Webform results link */
  $handler->display->display_options['fields']['webform_results_2']['id'] = 'webform_results_2';
  $handler->display->display_options['fields']['webform_results_2']['table'] = 'node';
  $handler->display->display_options['fields']['webform_results_2']['field'] = 'webform_results';
  $handler->display->display_options['fields']['webform_results_2']['relationship'] = 'nid';
  $handler->display->display_options['fields']['webform_results_2']['label'] = 'table';
  $handler->display->display_options['fields']['webform_results_2']['text'] = 'table';
  $handler->display->display_options['fields']['webform_results_2']['subpath'] = 'table';
  /* Field: Webform: Webform results link */
  $handler->display->display_options['fields']['webform_results_3']['id'] = 'webform_results_3';
  $handler->display->display_options['fields']['webform_results_3']['table'] = 'node';
  $handler->display->display_options['fields']['webform_results_3']['field'] = 'webform_results';
  $handler->display->display_options['fields']['webform_results_3']['label'] = 'download';
  $handler->display->display_options['fields']['webform_results_3']['text'] = 'download';
  $handler->display->display_options['fields']['webform_results_3']['subpath'] = 'download';
  /* Field: Webform: Webform edit link */
  $handler->display->display_options['fields']['webform_edit']['id'] = 'webform_edit';
  $handler->display->display_options['fields']['webform_edit']['table'] = 'node';
  $handler->display->display_options['fields']['webform_edit']['field'] = 'webform_edit';
  $handler->display->display_options['fields']['webform_edit']['label'] = 'Operations';
  $handler->display->display_options['fields']['webform_edit']['text'] = 'components';
  $handler->display->display_options['fields']['webform_edit']['subpath'] = 'components';
  /* Field: Webform: Webform edit link */
  $handler->display->display_options['fields']['webform_edit_2']['id'] = 'webform_edit_2';
  $handler->display->display_options['fields']['webform_edit_2']['table'] = 'node';
  $handler->display->display_options['fields']['webform_edit_2']['field'] = 'webform_edit';
  $handler->display->display_options['fields']['webform_edit_2']['label'] = 'clear';
  $handler->display->display_options['fields']['webform_edit_2']['text'] = 'clear';
  $handler->display->display_options['fields']['webform_edit_2']['subpath'] = 'clear';
  /* Field: Content: Edit link */
  $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
  $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
  $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'webform' => 'webform',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Content: Nid */
  $handler->display->display_options['filters']['nid']['id'] = 'nid';
  $handler->display->display_options['filters']['nid']['table'] = 'node';
  $handler->display->display_options['filters']['nid']['field'] = 'nid';
  $handler->display->display_options['filters']['nid']['group'] = 1;
  $handler->display->display_options['filters']['nid']['exposed'] = TRUE;
  $handler->display->display_options['filters']['nid']['expose']['operator_id'] = 'nid_op';
  $handler->display->display_options['filters']['nid']['expose']['label'] = 'Nid';
  $handler->display->display_options['filters']['nid']['expose']['operator'] = 'nid_op';
  $handler->display->display_options['filters']['nid']['expose']['identifier'] = 'nid';
  $handler->display->display_options['filters']['nid']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
    10 => 0,
    8 => 0,
    7 => 0,
    5 => 0,
    6 => 0,
    9 => 0,
    4 => 0,
  );
  /* Filter criterion: Field: Title (title_field) */
  $handler->display->display_options['filters']['title_field_value']['id'] = 'title_field_value';
  $handler->display->display_options['filters']['title_field_value']['table'] = 'field_data_title_field';
  $handler->display->display_options['filters']['title_field_value']['field'] = 'title_field_value';
  $handler->display->display_options['filters']['title_field_value']['relationship'] = 'reverse_field_edition_node';
  $handler->display->display_options['filters']['title_field_value']['exposed'] = TRUE;
  $handler->display->display_options['filters']['title_field_value']['expose']['operator_id'] = 'title_field_value_op';
  $handler->display->display_options['filters']['title_field_value']['expose']['label'] = 'Title';
  $handler->display->display_options['filters']['title_field_value']['expose']['operator'] = 'title_field_value_op';
  $handler->display->display_options['filters']['title_field_value']['expose']['identifier'] = 'title_field_value';
  $handler->display->display_options['filters']['title_field_value']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    6 => 0,
    10 => 0,
    8 => 0,
    3 => 0,
    5 => 0,
    4 => 0,
    7 => 0,
    9 => 0,
  );

  /* Display: Products List */
  $handler = $view->new_display('page', 'Products List', 'products');
  $handler->display->display_options['path'] = 'admin/dashboard/webforms';
  $handler->display->display_options['menu']['type'] = 'normal';
  $handler->display->display_options['menu']['title'] = 'Webforms';
  $handler->display->display_options['menu']['weight'] = '0';
  $handler->display->display_options['menu']['name'] = 'menu-admin-menu';
  $handler->display->display_options['menu']['context'] = 0;
  $handler->display->display_options['menu']['context_only_inline'] = 0;
  $translatables['dashboard_souriau_webforms'] = array(
    t('Master'),
    t('Products List'),
    t('more'),
    t('Apply'),
    t('Reset'),
    t('Sort by'),
    t('Asc'),
    t('Desc'),
    t('Items per page'),
    t('- All -'),
    t('Offset'),
    t('« first'),
    t('‹ previous'),
    t('next ›'),
    t('last »'),
    t('Nid'),
    t('Title'),
    t('[title]'),
    t('Type'),
    t('Updated date'),
    t('Submissions Count'),
    t('View'),
    t('submissions'),
    t('analysis'),
    t('table'),
    t('download'),
    t('Operations'),
    t('components'),
    t('clear'),
    t('Edit link'),
  );
  $export['dashboard_souriau_webforms'] = $view;

  $view = new view();
  $view->name = 'unused_contact_form_files';
  $view->description = 'List of unused webform files used for cron job deletion';
  $view->tag = 'default';
  $view->base_table = 'file_managed';
  $view->human_name = 'unused contact form files';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'unused form files';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'none';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Relationship: File: File usage (node) */
  $handler->display->display_options['relationships']['node_usage']['id'] = 'node_usage';
  $handler->display->display_options['relationships']['node_usage']['table'] = 'views_entity_file';
  $handler->display->display_options['relationships']['node_usage']['field'] = 'node_usage';
  /* Field: File: File ID */
  $handler->display->display_options['fields']['fid']['id'] = 'fid';
  $handler->display->display_options['fields']['fid']['table'] = 'file_managed';
  $handler->display->display_options['fields']['fid']['field'] = 'fid';
  /* Filter criterion: File: Path */
  $handler->display->display_options['filters']['uri']['id'] = 'uri';
  $handler->display->display_options['filters']['uri']['table'] = 'file_managed';
  $handler->display->display_options['filters']['uri']['field'] = 'uri';
  $handler->display->display_options['filters']['uri']['operator'] = 'contains';
  $handler->display->display_options['filters']['uri']['value'] = '/webform/contact_attachements/';
  $handler->display->display_options['filters']['uri']['group'] = 1;
  /* Filter criterion: File Usage: Use count */
  $handler->display->display_options['filters']['count']['id'] = 'count';
  $handler->display->display_options['filters']['count']['table'] = 'file_usage';
  $handler->display->display_options['filters']['count']['field'] = 'count';
  $handler->display->display_options['filters']['count']['operator'] = 'empty';
  $handler->display->display_options['filters']['count']['value']['value'] = '0';
  /* Filter criterion: File: Upload date */
  $handler->display->display_options['filters']['timestamp']['id'] = 'timestamp';
  $handler->display->display_options['filters']['timestamp']['table'] = 'file_managed';
  $handler->display->display_options['filters']['timestamp']['field'] = 'timestamp';
  $handler->display->display_options['filters']['timestamp']['operator'] = '<';
  $handler->display->display_options['filters']['timestamp']['value']['value'] = '-2 hours';
  $handler->display->display_options['filters']['timestamp']['value']['type'] = 'offset';
  $translatables['unused_contact_form_files'] = array(
    t('Master'),
    t('unused form files'),
    t('more'),
    t('Apply'),
    t('Reset'),
    t('Sort by'),
    t('Asc'),
    t('Desc'),
    t('File usage (node)'),
    t('File ID'),
  );
  $export['unused_contact_form_files'] = $view;

  return $export;
}
